Feature/eckit sparsematrix allocators reorganization, new in-place allocator
ecmwf/eckit pull request #148
Opened 2024-11-13 13:33 UTC by pmaciel

This add a new "allocator" to the SparseMatrix, which allows building one with direct, non-owned access to a set of Index*, Index* and Scalar*.

It allows low-level control of the data structures, benefiting the following:
- to provide views, hence promoting parallelism
- efficient handling of very large cases, by exploiting the internal structure (per-row assembly, non-linear corrections, etc.)
- creation of utilities that observe and manipulate the structure directly (reordering, manipulation of weights, etc.)

There's no urgency

2024-11-29 11:06 UTC, pmaciel commented
Say a few more days before merge? I have changes depending on this.

2024-11-29 15:31 UTC, wdeconinck requested changes
I think this is great! A few points.

minor point: I would change to something like "NonOwningAllocator" or "WrappingAllocator"

more significant point:
When the SparseMatrix is created this way, wrapping existing data, the user of this class should not be allowed to call several methods:
- `SparseMatrix::reserve(rows, cols, nnz)`
- `SparseMatrix::load()`
- `SparseMatrix::transpose()`
- `SparseMatrix::setIdentity()`
- `SparseMatrix::prune()`

In fact anything that is attempting to change the shape should be forbidden.

One option is to add a boolean flag to `SparseMatrix::Shape` be set by the Allocator which can be checked if changes to shape are allowed or not. Open to other suggestions.

2024-11-29 15:31 UTC, wdeconinck commented on src/eckit/linalg/allocator/InPlaceAllocator.cc
> +    layout.outer_ = reinterpret_cast<decltype(SparseMatrix::Layout::outer_)>(ia_);
I believe a reinterpret_cast or const_cast or any other casting should not be necessary.

2024-12-09 09:06 UTC, wdeconinck commented on src/eckit/linalg/allocator/InPlaceAllocator.cc
> +    layout.outer_ = reinterpret_cast<decltype(SparseMatrix::Layout::outer_)>(ia_);
I understood now that the reinterpret_cast is a byproduct of a PR from a few months back where the data type of outer_ has changed from Index to UIndex.

2025-02-18 17:08 UTC, wdeconinck approved these changes
OK I agree that it is ambiguous what needs to happen with e.g. the `matrix.transpose()` case when using the non-owning allocator. It had bitten me that the wrapped memory became in a corrupt or undefined state because of such function, and without any warning.

This can be left for future pain and frustration ¯\_(ツ)_/¯ 
I'm OK for this to be merged now.

2025-02-19 16:12 UTC, merged