Feature/mpi sendrecv replace
ecmwf/eckit pull request #57
Opened 2023-02-22 08:10 UTC by andreapiacentini

This is a tentative implementation of issue #53  
It most probably will require some adjustment by the reviewers, especially for the Serial implementation.  
Nevertheless, this feature is quite urgently needed for an oops development.
Thanks

2023-02-22 08:10 UTC, FussyDuck commented
[![CLA assistant check](http://claassistant.ecmwf.int:80/pull/badge/not_signed)](http://claassistant.ecmwf.int:80/ecmwf/eckit?pullRequest=57) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](http://claassistant.ecmwf.int:80/ecmwf/eckit?pullRequest=57) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](http://claassistant.ecmwf.int:80/check/ecmwf/eckit?pullRequest=57) it.</sub>

2023-02-27 09:33 UTC, wdeconinck commented
Hello @andreapiacentini that looks good to me.
But please could you add a unit test both for parallel and serial execution?
I will then test it out locally with MPI before approving, because the eckit Github-actions-CI does not use MPI (yet).

2023-02-27 09:34 UTC, wdeconinck requested changes
Unit-test required

2023-02-27 09:46 UTC, wdeconinck commented
@dtip do you have any clue why CI is failing? It does not seem related to this PR.

2023-02-27 14:27 UTC, dtip commented
> @dtip do you have any clue why CI is failing? It does not seem related to this PR.

Yep, it's a permissions issue with accessing the secrets we need to run CI from this public PR. We'll update the CI shortly to fix it.

2023-02-27 14:29 UTC, dtip commented
@wdeconinck do we want to also modify the CI to compile and test both with and without MPI enabled?

2023-02-27 14:31 UTC, andreapiacentini commented
@wdeconinck I've commited unit tests for these features.  
The MPI test passes and I am happy with that.  
The serial test passes too and I am pleasantly astonished. It passes as well if I comment out all the contents of the serial implementation of sendReceiveReplace and I just return an empty Status.  
Most probably it is telling me that a "Replace" function is completely meaningless in serial mode. What do you think?  
If you agree on that, please proceed to clipping the serial implementation.

2023-02-27 15:46 UTC, dtip commented
We've (hopefully) just fixed the CI issue in https://github.com/ecmwf/eckit/pull/58

@andreapiacentini could you rebase this PR onto the latest `develop` branch please, then @wdeconinck can approve the CI run.

2023-02-27 16:15 UTC, andreapiacentini commented
@dtip I did it via the github "Sync fork" link.  
I hope it worked ok.  
Thanks

2023-02-27 16:22 UTC, tlmquintino commented
> > @wdeconinck do we want to also modify the CI to compile and test both with and without MPI enabled?
> 
> I would definitely suggest to enable MPI. For Atlas and fckit this was enough reason to build eckit as an internal CI cache rather than reuse an existing artifact. It would also be able to test MPI feature changes here rather than offline.

I think we need to have test with and without MPI. This should be part of the matrix of builds, and we did discuss the possibility of having different builds based on _options_ not only on platforms x compilers.

2023-02-27 16:24 UTC, dtip commented
> I think we need to have test with and without MPI. This should be part of the matrix of builds, and we did discuss the possibility of having different builds based on _options_ not only on platforms x compilers.

Exactly - we can build both with and without MPI with a matrix of build options.

2023-02-28 10:20 UTC, wdeconinck commented
@dtip something is not right with the GitHub token

2023-02-28 10:39 UTC, dtip commented
@wdeconinck Yep, the fix we made yesterday didn't work so we've had to revert it. If you're confident with the PR, please feel free to merge it. Otherwise, if you want to run CI, the temporary workaround is to push the come from this PR to a branch within the `eckit` repo, then open a new PR.

2023-02-28 10:51 UTC, merged