{WIP} Correct mscOS specific downstream issues
ecmwf/eckit pull request #90
Opened 2023-11-22 11:09 UTC by marcosbento

Re ECKIT-620

2023-11-22 13:59 UTC, pmaciel commented
I've taken the chance to further fix the build (re. templates + ecbuild), cleanup the include hierarchy and make the proprocessor directives consistent.

This was already a good cleanup, I just added a few sprinkles :-)

2023-11-23 09:17 UTC, wdeconinck requested changes

2023-11-23 09:17 UTC, wdeconinck commented on src/eckit/option/FactoryOption.cc
I notice this file with `.cc` ext gets #included in `FactoryOption.h`
This is the wrong ext and compiler will try to compile this file directly.
Instead the ext could be `tcc` (for template cc)
See e.g. https://github.com/ecmwf/ecbuild/blob/develop/cmake/ecbuild_separate_sources.cmake#L35C2-L35C2
Where this file then also gets recognised as header file.

2023-11-23 09:25 UTC, pmaciel commented on src/eckit/option/FactoryOption.cc
Yes, that's true for FactoryOption.cc, VectorOption.cc and SimpleOption.cc (and likely, many other places in the code)

Then, these should also be removed from the respective (src/eckit/optios/CMakeLists.txt ecbuild_add_library) SOURCES and only present in the TEMPLATES part.

2023-11-23 10:16 UTC, wdeconinck commented on src/eckit/option/FactoryOption.cc
Or as mentioned, tcc ext will also automatically work. As you choose.

2023-11-23 10:18 UTC, wdeconinck approved these changes

2023-11-23 10:28 UTC, marcosbento commented on src/eckit/option/FactoryOption.cc
Looking at the `ecbuild_add_library` implementation, we have 2 options:
(a) #include .cc files, and tens list them as SOURCES and TEMPLATES when calling ecbuild_add_library
(b) have .tcc sources included as #include .tcc files, and then list them only as SOURCES , and let `ecbuild_add_library` automatically sort these template files out.

2023-11-23 10:41 UTC, marcosbento commented on src/eckit/option/FactoryOption.cc
eckit seems to be following approach (a). I don't find any .tcc file in the code base.

I'm happy to align with approach (b) and make all necessary eckit updated in the future, but I not sure we should use this PR to make those changes.

2023-11-23 12:41 UTC, wdeconinck commented
Failure in pgen, but not a bug in eckit:
```
In file included from ../src/tools/pgen-compare.cc:17:
  ../src/pgen/compare/CompareProducer.h:88:18: error: ‘set’ in namespace ‘std’ does not name a template type
     88 |     mutable std::set<std::string> shown_;
        |                  ^~~
  ../src/pgen/compare/CompareProducer.h:24:1: note: ‘std::set’ is defined in header ‘<set>’; did you forget to ‘#include <set>’?
  ```

2023-11-23 12:43 UTC, wdeconinck commented on src/eckit/option/FactoryOption.cc
Yes better to stay consistent with eckit style

2023-11-27 13:58 UTC, wdeconinck commented
I created PR in pgen @danovaro to address above issue.

2023-11-28 13:57 UTC, merged